from ftplib import *
import os
import time
from ftps import *

def ftps_upload(host, user, passw, folders, local_path, ftps_folder, log_file):
    """
    Uploads all the files from the folders inside the
    local_path into the ftps_folder. If it fails it writes the failure
    in the log_file
    """
    
    connection="CONNECTION FAIL"
    try:
            ftps=tyFTP()
            ftps.connect(host=host, port=38990)
            ftps.login(user=user, passwd=passw)
            ftps.prot_p()

            connection="CONNECTION OK"
            for carpeta in folders:
                    for file in os.listdir(local_path + carpeta):
                            fp=open(local_path + carpeta + "\\" + file, 'rb')
                            ftps.storlines("STOR /" + ftps_folder +
                                           "/" + file, fp)
                            fp.close()
                            os.rename(local_path+carpeta + "\\" +
                                      file, local_path + file)

            ftps.close()
                            
                            

    except:
            log_file = open(log_file, 'w')
            current_date = time.strftime("%x")
            log_file.write("Error " + carpeta + " " + current_date +
                           ";" + connection)
            log_file.close()
